build-dev:
  image: docker:latest
  stage: build
  environment: development
  tags:
    - docker
  script:
    - docker login registry.gitlab.com -u $CI_BUILD_USER -p $CI_BUILD_TOKEN
    - docker build -t registry.gitlab.com/neotericeu/three-leaf/threeleaf-backend:develop .
    - docker push registry.gitlab.com/neotericeu/three-leaf/threeleaf-backend:develop
  only:
    - develop
