version: "3.0"
services:
  threeleaf:
    image: 180122916419.dkr.ecr.eu-west-1.amazonaws.com/threeleaf:develop
    restart: on-failure
    ports:
      - "80:1337"
    logging:
      driver: awslogs
      options:
        awslogs-group: threeleaf
        awslogs-region: us-east-1
        awslogs-stream-prefix: threeleaf
